version: '3.5'

services:

    api:
      container_name: php_cbc
      # image: php-composer:7.4
      command: sh -c "php artisan key:generate && php artisan && php artisan serve --host=0.0.0.0"
      working_dir: /app
      build:
        dockerfile: Dockerfile
        context: .
      ports:
        - 9000:8000
      depends_on:
        - db
      volumes:
        - ./app:/app
      # env_file:
      #   - ./app/.env

    db:
        container_name: db_cbc 
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
          - 2000:3306
        volumes:
            - /var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cbc
